# 1. 数组间运算

1. 数组元素切片
2. 改变数组形状
3. 加法
4. 乘法
5. 转置与求逆

## 数组元素切片

In [1]:
import numpy as np

# 一维数组切片
a = np.array([0,1,2,3])
print(a[:2])
# 二维数组切片
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(b[1:3]) # 第2,3行
print(b[1:2,1:3]) # 第2行 第2，3列
# 三维数组切片
c = np.array([
    [
        [0,1,2,3],
        [4,5,6,7],
        [8,9,10,11]
    ],
    [
        [12,13,14,15],
        [16,17,18,19],
        [20,21,22,23]
    ]
])
print(c[:1,:1,1:3]) # 第一层 第一行 第2，3列

[0 1]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[5 6]]
[[[1 2]]]


### 改变数组的形状

`np.reshape(shape)`：不改变当前数组，根据shape重新创建新的数组

`np.resize(shape)`：改变当前数组

In [4]:
origin = np.arange(12)
origin.reshape(3,4)
print(origin)
origin.resize(2,6)
print(origin)
converted = origin.reshape(-1,3) # 当shape中的参数被设置为-1时 即表示根据元素个数自动计算
print(converted)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 加法运算 (+)

- 相加的2个数组的形状和长度应该一致，否则就会出错
- 一维数组可以和多维数组相加，相加时会将一维数组扩展至多维

In [16]:
# 相同长度的加法
pa = np.arange(4)
pb = np.arange(2,6)
pr = pa + pb
print('a:',pa)
print('b:',pb)
print('r:',pr)

print('-'*21)
# 一维 + 多维

pc =  np.arange(8).reshape(2,4)
print('a:',pa)
print('c:',pc)
pr2 = pa + pc
print('r2:',pr2)

a: [0 1 2 3]
b: [2 3 4 5]
r: [2 4 6 8]
---------------------
a: [0 1 2 3]
c: [[0 1 2 3]
 [4 5 6 7]]
r2: [[ 0  2  4  6]
 [ 4  6  8 10]]


### 矩阵乘法

- 乘号运算符：矩阵中对应元素分别相乘（运算符为 `*` ）
- 矩阵相乘：按照矩阵相乘的规则运算（运算符为 `np.matmul(A,B)`或者`np.dot(A,B)`）

In [20]:
# 乘号运算符
ma = np.array([[1,1],
               [0,1]])
mb = np.array([[2,0],
               [3,4]])
mr = ma * mb
print(ma,'*')
print(mb,'=')
print(mr)
print('-'*21)
# 矩阵乘法
mr2 = np.matmul(ma,mb)
print(mr2)

[[1 1]
 [0 1]] *
[[2 0]
 [3 4]] =
[[2 0]
 [0 4]]
---------------------
[[5 4]
 [3 4]]


### 转置与求逆

转置：`np.transpose()`，求逆：`np.linalg.inv()`

In [23]:
A = np.array([[1,2],
              [3,4]])
A1 = np.transpose(A)
A2 = np.linalg.inv(A)
print(A1)
print(A2)

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# 2. 数组元素间运算

| 函数 | 功能描述 |
| :---- | :----|
| np.sum() | 计算所有元素的和 |
| np.prod() | 计算所有元素的乘积 |
| np.diff() | 计算数组相邻元素之间的差 |
| np.sqrt() | 计算各元素的平方根 |
| np.exp() | 计算各元素的指数值 |
| np.abs() | 取各元素的绝对值 |